### ISSUE TITLE
wow lol

### ISSUE THREAD

**Issue by sparta34** [ResidualLaugh/cobaltstrike3.13#1]
thanks man you are the best

**Comment by sparta34** [comment]
listeners is not working !!

**Comment by ResidualLaugh** [comment]
Yes, I just found that. I will find out the reason maybe someday I have time.

**Comment by ResidualLaugh** [comment]
I should have corrected some wrong code. Tomorrow I will try to fix it.

**Comment by sparta34** [comment]
ok good luck

**Comment by ResidualLaugh** [comment]
Fortunately, the problem was found. The trial version did not have xorencode, but when it was cracked, it tried to add this function, and found that it was not applicable to version 3.13, so I did not modify this part of the content.

**Comment by sparta34** [comment]
oh ok thanks for your time and happy hacking lol
